
qriollo : Infer.hs Deps.hs ExpressionK.hs Env.hs Backend Backend/C.hs Backend/C_MM.hs Backend/Jvm.hs Backend/Py.hs Backend/JvmClass.hs Constraints.hs Parser.hs Position.hs ExpressionL.hs Unify.hs Eval.hs RegAlloc.hs Main.hs Closure.hs Compress.hs Lexer.hs Optim.hs Reader.hs ExpressionE.hs CPS.hs Makefile Precompiler.hs Invariants.hs QriolloEval.hs Primitive.hs AST.hs
	ghc --make Main.hs -o qriollo
