
qriollo : src/Infer.hs src/Deps.hs src/ExpressionK.hs src/Env.hs src/Backend src/Backend/C.hs src/Backend/C_MM.hs src/Backend/Jvm.hs src/Backend/Py.hs src/Backend/JvmClass.hs src/Constraints.hs src/Parser.hs src/Position.hs src/ExpressionL.hs src/Unify.hs src/Eval.hs src/RegAlloc.hs src/Main.hs src/Closure.hs src/Compress.hs src/Lexer.hs src/Optim.hs src/Reader.hs src/ExpressionE.hs src/CPS.hs src/Precompiler.hs src/Invariants.hs src/QriolloEval.hs src/Primitive.hs src/AST.hs
	ghc --make src/Main.hs -isrc/ -o qriollo
