RES *fu_eq(RES *v, RES *w);
RES *fu_null(RES *v);
RES *fu_map(RES *f, RES *l);
RES *fu_mapc(RES *f, RES *l);
RES *fu_maplist(RES *f, RES *l);
RES *fu_mapl(RES *f, RES *l);
RES *fu_mapt(RES *f, RES *l);
RES *fu_length(RES *v);
RES *fu_rev(RES *v);
RES *fu_xrev(RES *v);
RES *fu_elt(RES *idx, RES *v);
RES *fu_elt_set(RES *idx, RES *v, RES *valor);
RES *fu_cat(RES *seqs);
RES *fu_join(RES *sep, RES *seqs);
RES *fu_copy_shallow(RES *v);
RES *fu_index(RES *elt, RES *v, RES *pred);
RES *fu_member(RES *elt, RES *v, RES *pred);
RES *fu_assoc(RES *elt, RES *v, RES *pred);
RES *fu_slice(RES *v, RES *inicio, RES *final, RES *step);
RES *fu_last(RES *lista);
RES *fu_range(RES *x, RES *y, RES *z);
RES *fu_iota(RES *x, RES *y, RES *z);
RES *fu_fread(RES *archivo);
RES *fu_fwrite(RES *archivo, RES *str);
RES *fu_flines(RES *archivo);
RES *fu_load(RES *archivo, RES *args);
RES *fu_import(RES *archivo, RES *args);
RES *fu_run(RES *archivo, RES *args);
RES *fu_die(RES *mensaje, RES *valor);
RES *fu_exit(RES *valor);
RES *fu_sys(RES *args);
RES *fu_call(RES *val, RES *args);
RES *fu_rand(RES *max);
RES *fu_choice(RES *seq, RES *n, RES *repeat);
RES *fu_list_to_vec(RES *v, RES *tamano);
RES *fu_list_to_str(RES *v, RES *tamano);
RES *fu_vec_to_list(RES *v);
RES *fu_any(RES *pred, RES *v);
RES *fu_all(RES *pred, RES *v);
RES *fu_not_all(RES *pred, RES *v);
RES *fu_not_any(RES *pred, RES *v);
RES *fu_dynl(RES *arch, RES *args);
RES *fu_os_type();
